use_frameworks!

target 'RxAlertController_Example' do
  pod 'RxAlertController', :path => '../'

  target 'RxAlertController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
