language: swift
osx_image: xcode10.3
script: carthage update RxSwift --platform iOS --no-build && sed -i -e 's/MACH_O_TYPE = mh_dylib/MACH_O_TYPE = staticlib/g' Carthage/Checkouts/RxSwift/Rx.xcodeproj/project.pbxproj && carthage build RxSwift --platform iOS && set -o pipefail && xcodebuild -project RxAlertController.xcodeproj -scheme RxAlertController -sdk iphonesimulator | xcpretty
